### ISSUE TITLE
Occupation Forces, Neither player can see each other

### ISSUE THREAD

**Issue by Mal0-1471** [unknown321/dynamite#26]
<img width="2211" height="664" alt="Image" src="https://github.com/user-attachments/assets/3242efe4-8b44-4df5-acd4-4f3437fdcfec" />

Players cannot see each other when in Occupation Forces, tested restarting multiple times. Over the Fence worked without issue.

**Comment by unknown321** [comment]
should be fixed now, hope you'll get the notification

**Comment by Mal0-1471** [comment]
<img width="2211" height="664" alt="Image" src="https://github.com/user-attachments/assets/cbd103b5-fada-4cea-b7a9-c2024b6fc284" />

Not fixed, same issue on Occupation Forces, neither player can see each other but can connect otherwise fine and stuff such as throwing mags still show up fine and are synced.

**Comment by unknown321** [comment]
Cannot reproduce, need more info.

<img width="1194" height="679" alt="Image" src="https://github.com/user-attachments/assets/4a8ea534-490a-437e-b7d2-7fce711bbcc3" />

<img width="723" height="449" alt="Image" src="https://github.com/user-attachments/assets/78e8fb3f-452c-4b50-be72-5dbe23dd8c75" />

Bottom left spawn works just fine. Are you on [latest version](https://github.com/unknown321/dynamite/releases/latest)? It must be at least v.0.2.2 for both client and host. Another thing - deploy at 06:00, can't see a thing on your screenshots.

**Comment by Mal0-1471** [comment]
We are both on 0.2.2 and we used the right-most helicopter spawn location.
I've been using 01800 since it's what i usually pick when playing normally, for future i'll use 0600.

**Comment by unknown321** [comment]
<img width="624" height="373" alt="Image" src="https://github.com/user-attachments/assets/153a225b-0dc9-4714-8b38-05c9b2539502" />

By rightmost you mean white one, not red Da Smasei one?

**Comment by Mal0-1471** [comment]
Yes i mean the safe ones, sorry i forgot there can be more if you cleared out the anti-air.

**Comment by unknown321** [comment]
<img width="1210" height="664" alt="Image" src="https://github.com/user-attachments/assets/903f6b0e-7cce-49c2-b63e-6f473fa850bc" />

Deployed on that spot, works. Please try to reinstall the mod by using "Save and reinstall" button on configuration screen in web UI.

**Comment by unknown321** [comment]
tank problems moved to another issue
